# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -g -O0 --coverage   -DGTEST_HAS_PTHREAD=1

CXX_DEFINES = -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"gas\"

CXX_INCLUDES = -I/home/sameep/catkin_ws/src/gas/include -I/opt/ros/noetic/include -I/opt/ros/noetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/usr/include/opencv4 -I/home/sameep/catkin_ws/src/gas/src -isystem /usr/src/googletest/googletest/include -isystem /usr/src/googletest/googletest 

